version: "2.4"
services:
  rabbitmq:
    image: rabbitmq:3-management
    restart: always
    ports: 
        - "5671:5671"
        - "15672:15672"
          
  eureka-server: 
    image: microservices/eureka-server
    restart: always
    ports: 
      - "8872:8872"
        
  auth-server: 
    image: microservices/auth-server
    restart: always
    ports: 
      - "8096:8096"
    depends_on:
      - eureka-server
       
  subscription-service:
    image: microservices/subscription-service
    restart: always
    ports: 
      - "8084:8084"
    depends_on:
      - rabbitmq
      - auth-server
      - eureka-server
          
  subscription-processor:
    image: microservices/subscription-processor
    restart: always
    depends_on:
      - eureka-server
      - rabbitmq 
      - auth-server 

  email-service:
    image: microservices/email-service
    restart: always
    depends_on:
      - eureka-server
      - rabbitmq
   
  subscription-app:
    image: microservices/subscription-application
    restart: always
    ports: 
      - "8082:8082"
    depends_on: 
      - eureka-server
      - subscription-service
      - auth-server
  
  zuul-server:
    image: microservices/zuul-server
    restart: always
    ports: 
      - "8085:8085"
    depends_on: 
      - eureka-server
  