server:
  port: 8089

spring:
  application:
    name: subscription-processor
  rabbitmq:
    addresses: rabbitmq:5672
    username: guest
    password: guest
    template:
      exchange: subscription-exchange
      default-receive-queue: subscription-queue
      routing-key: subscription.create
    listener:
      simple:
        concurrency: 5
        max-concurrency: 10
        prefetch: 1

security:
    basic:
      enabled: false
    oauth2:
      client:
          subscription:
            clientId: subscription-service
            clientSecret: $ubscR1pT10NCl13nt
            authorized-grant-type: client_credentials
            scope: openid
            token-uri: http://auth-server:8096/oauth/token

adapter:
  max-retry: 10

subscription-service:
  endpoint: http://zuul-server:8085/subscription-service/api/subscription/
  
eureka: 
  client:
    service-url:
      defaultZone: http://eureka-server:8872/eureka/
      
logging:
  level:
    ROOT: INFO
    org.springframework.web: DEBUG