
server:
    port: 8084

eureka: 
  client:
    service-url:
      defaultZone: http://localhost:8872/eureka/
    
security:
    oauth2:
      client:
        authorized-grant-types:
        - client_credentials
        client-secret: $ubscr1Pt10N
        client-id: subscription-service
        access-token-uri: http://localhost:8096/oauth/token
        user-authorization-uri: http://localhost:8096/oauth/authorize
      resource:
        user-info-uri: http://localhost:8096/user
            

spring:     
  application:
    name: subscription-service 
  datasource:
    url: 
    username: test
    password: test
  rabbitmq:
    addresses: localhost:5672
    username: guest
    password: guest
    template:
      exchange: subscription-exchange
      default-receive-queue: subscription-queue
      routing-key: subscription.create
    listener:
      simple:
        concurrency: 5
        max-concurrency: 10
        prefetch: 1
  data:
    mongodb:
      uri: mongodb+srv://test:test123@cluster0.py1gb.mongodb.net/subscription?retryWrites=true&w=majority       
email: 
  routing-key: subscription.email
        
logging:
  level:
    ROOT: INFO
    org.springframework.web: DEBUG        