server:
  port: 8090

spring:
  application:
    name: email-service
  rabbitmq:
    addresses: rabbitmq:5672
    username: guest
    password: guest
    template:
      exchange: subscription-exchange
      default-receive-queue: email-queue
      routing-key: subscription.email
    listener:
      simple:
        concurrency: 5
        max-concurrency: 10
        prefetch: 1

adapter:
  max-retry: 10
 
eureka: 
  client:
    service-url:
      defaultZone: http://eureka-server:8872/eureka/
      
logging:
  level:
    ROOT: INFO
    org.springframework.web: DEBUG